fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: uncrustify
        args: [--replace, --no-backup, -c, uncrustify.cfg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix]
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
    - id: remove-tabs
      args: [--whitespaces-count, '4']
